### ISSUE TITLE
handle situation when grant was removed by user from accounts.google.com

### ISSUE THREAD

**Issue by ivan-ushakov** [FlowCrypt/flowcrypt-ios#1048] opened 2021-11-20 07:31 UTC
I got this screen when I started app today (`e2e.enterprise.test` user):

![Simulator Screen Shot - iPhone 11 Pro - 2021-11-20 at 10 29 18](https://user-images.githubusercontent.com/1408366/142718477-2e7b27c4-10f8-4b11-9968-6d733bbd1af3.png)

Maybe something with oAuth token expiration?

**Comment by tomholub** [comment] 2021-11-20 07:43
oauth token is provided by google and then used to authenticate with other services, like EKM. 

Here you are calling Google itself, oauth token should not be involved. I suppose you've seen it once and it went away?

Did tapping retry help? (I suppose not)
Did re-authenticating help (I suppose yes)

Maybe just the access token expired, and we don't handle renewal properly. 

Or maybe someone went to accounts.google.com -> security and removed iOS grant while you were using the app.

**Comment by ivan-ushakov** [comment] 2021-11-20 18:17
> Did tapping retry help? (I suppose not)
No, I got the same error screen

**Comment by tomholub** [comment] 2021-11-25 16:58
Have you been encountering this again?

**Comment by tomholub** [comment] 2021-11-25 17:00
Anyway this can be reproduced by going to account.google.com and revoking your grant from the iOS app. Something we have to fix either way.

The handling should be to show a "missing permission screen" like we do for contacts, where use can click / re authenticate.

And this is for all Gmail API calls. So it has to be universal, done for each Task that handles Gmail API calls.

**Comment by ioanmo226** [comment] 2022-03-30 14:08
@tomholub For this case, I think it's better to just logout user (and show intro screen if there's no other account or show another inbox) and inform user with alert like this.
`Your account xxx was logged out because app grant was removed.`

If we try to re-authenticate user, logic will be complex.
User might not select `gmail` permission during re-authentication, or user might cancel reauthentication, etc.

Let me know your thoughts

**Comment by ioanmo226** [comment] 2022-03-30 16:21
OK, Got it

**Comment by ioanmo226** [comment] 2022-03-31 07:13
@tomholub I can see that this issue is duplicate of #839 and that task is marked as `In Progress` by @sosnovsky.
@sosnovsky Have you already started work on this?

**Comment by tomholub** [comment] 2022-03-31 09:57
Whoops. Sorry about the duplicate.

**Comment by sosnovsky** [comment] 2022-04-04 13:33
> @tomholub No problem. I think we may close this issue if it's already done/WIP by @sosnovsky.

Yes, I'm currently working on #839, so this issue can be closed as duplicated.

**Closed by sosnovsky** 2022-04-04 13:33 UTC
Labels: bug, actionable
