### ISSUE TITLE
Crash when opening Contacts screen

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#910] opened 2021-11-04 09:44 UTC
App crashes every time when I try to open Contacts screen. It's `Realm accessed from incorrect thread` error again

<img width="1392" alt="Screenshot 2021-11-04 at 11 42 44" src="https://user-images.githubusercontent.com/1062093/140291918-0de00470-0378-4ff2-a557-6d349a28a73b.png">

**Comment by tomholub** [comment] 2021-11-04 09:49
related #877

**Comment by tomholub** [comment] 2021-11-04 09:55
Also this needs an updated UI test else it wouldn't get broken. The test from https://github.com/FlowCrypt/flowcrypt-ios/issues/718 should get updated to:

 - go to app Settings -> Contacts screen and verify there is no contact or public key for the person you are about to search
 - search a name that has a public key findable
 - go to app Settings -> Contacts screen and verify the public key got loaded, and make the fingerprint and other key information part of the test (don't make separate constants for this, hard-code it in the test directly) 

I'll file a separate issue.

**Comment by tomholub** [comment] 2021-11-09 11:08
Could you check why did this test not discover it? https://github.com/FlowCrypt/flowcrypt-ios/pull/943

**Comment by tomholub** [comment] 2021-11-09 12:34
I suppose this would be fore @ivan-ushakov

**Comment by sosnovsky** [comment] 2021-11-09 12:39
> Could you check why did this test not discover it? #943

Crash happens only when there is more than 1 contact stored in the app.
UI test has only 1 contact added, so app works well and test passes. Adding another contact should make test fail, I think.

**Comment by tomholub** [comment] 2021-11-09 13:24
@ivan-ushakov please first update the ui test to reproduce the crash (search for two recipients on the compose screen). Then fix the crash after that. That way we know our tests will help us next time.

**Comment by ivan-ushakov** [comment] 2021-11-09 14:26
> @ivan-ushakov please first update the ui test to reproduce the crash (search for two recipients on the compose screen). Then fix the crash after that. That way we know our tests will help us next time.

This requires to have several contacts. First one is `dmitry`. What about second one?

**Comment by tomholub** [comment] 2021-11-09 15:05
You can use demo@flowcrypt.com as a recipient to load a second contact

**Comment by ivan-ushakov** [comment] 2021-11-09 15:35
@tomholub 
Currently first UI test does not work. For some reason it asks for pass phrase at Compose screen while test expects to enter email. So it enters email into pass phrase alert.

![Simulator Screen Shot - appiumTest-9D7CBD23-6790-436E-926D-CA189C5C5DAC-iPhone X - 2021-11-09 at 18 33 51](https://user-images.githubusercontent.com/1408366/140954684-e773eb26-836d-4a90-a30c-150d6735d35a.png)

**Comment by ivan-ushakov** [comment] 2021-11-09 15:45
> It's asking for pass phrase for message signing, which is not wrong.

If it is OK, why it was working for previous PR's?

**Comment by tomholub** [comment] 2021-11-09 15:54
I have no clue. Can you try to run the test on master?

**Comment by ivan-ushakov** [comment] 2021-11-09 15:56
> I have no clue (and was also wondering). Can you try to run the test on master?

I'm on actual master branch

**Comment by tomholub** [comment] 2021-11-09 15:59
Which exact test is it? I'll try it here.

**Comment by ivan-ushakov** [comment] 2021-11-09 16:01
> Which exact test is it? I'll try it here.

I run all tests with `npm run-script only.test.all`. Looks like this happens because of new logic with draft. Do we support draft logic in `new-message.screen.ts`?

**Comment by tomholub** [comment] 2021-11-09 16:10
> > Which exact test is it? I'll try it here.
> 
> I run all tests with `npm run-script only.test.all`. Looks like this happens because of new logic with draft. Do we support draft logic in `new-message.screen.ts`?

Normally yes - if any PR makes it to master, it has to pass tests first.

Unless - theoretically - the PR was not updated to master before being merged. Eg the tests run and pass week ago, master changed, and then tests are merged. That could break them. Maybe that's what happened here.

**Comment by ivan-ushakov** [comment] 2021-11-09 16:14
I don't see any logic for draft pass phrase alert in `new-message.screen.ts`. @fcvakintos could you please take a look?

**Comment by tomholub** [comment] 2021-11-09 21:26
For reference - I'm disabling the drafts functionality, so @fcvakintos doesn't have to be fixing this right now. By the time we re-enable drafts, we'll have a more appropriate implementation, and the existing ui tests should be ok with it.

**Closed** 2021-11-10 15:45 UTC
Labels: bug, actionable, in progress, PR Submitted
