### ISSUE TITLE
Empty draft issue

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#962] opened 2021-11-09 11:12 UTC
Draft is saved when user just opened Compose screen and didn't enter anything.

Example:
1. Open thread
2. Tap "Reply"
3. Go back to Inbox screen - messages counter for this thread increased by 1
4. Open the same thread - now there is an empty message in the end (which is empty draft)

**Comment by tomholub** [comment] 2021-11-09 11:16
Thanks! It's a duplicate of #887 - also bothers me.

**Closed by tomholub** 2021-11-09 11:16 UTC
Labels: actionable
